### ISSUE TITLE
Add ISSUE_TEMPLATEs to standardize bugs/feature/requests and other type of issues

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#100]
[Using Issue templates ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)in GitHub makes it easier for new contributors to file better issues. Let's implement some standards here.

**Comment by afragen** [comment]
## Bug Report
### Description
Describe the bug.

### Environment
- WordPress: 6.7-RC1
- PHP: 7.4.30
- Server: nginx/1.26.1
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 7.4.30)
- Browser: Safari 18.0.1
- OS: macOS
- Theme: Twenty Twelve 4.3
- MU Plugins: None activated
- Plugins:
  * Core Rollback 1.3.6
  * Local Development 2.9.0
  * Test Reports 1.2.0
  * WordPress Beta Tester 3.6.1

### Steps to Reproduce
1. 
2. 🐞 Bug occurs.

### Expected Results
1.  ✅ What should happen.

### Actual Results
1.  ❌ What actually happened.

### Additional Notes
- Any additional details worth mentioning.

### Supplemental Artifacts
Add as Attachment

**Comment by afragen** [comment]
## Reproduction Report
### Description
This report validates whether the issue can be reproduced.

### Environment
- WordPress: 6.7-RC1
- PHP: 7.4.30
- Server: nginx/1.26.1
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 7.4.30)
- Browser: Safari 18.0.1
- OS: macOS
- Theme: Twenty Twelve 4.3
- MU Plugins: None activated
- Plugins:
  * Core Rollback 1.3.6
  * Local Development 2.9.0
  * Test Reports 1.2.0
  * WordPress Beta Tester 3.6.1

### Actual Results
1.  ✅ Error condition occurs (reproduced).

### Additional Notes
- Any additional details worth mentioning.

### Supplemental Artifacts
Add as Attachment

**Comment by afragen** [comment]
## Test Report
### Description
This report validates whether the indicated patch works as expected.

Patch tested: REPLACE_WITH_PATCH_URL

### Environment
- WordPress: 6.7-RC1
- PHP: 7.4.30
- Server: nginx/1.26.1
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 7.4.30)
- Browser: Safari 18.0.1
- OS: macOS
- Theme: Twenty Twelve 4.3
- MU Plugins: None activated
- Plugins:
  * Core Rollback 1.3.6
  * Local Development 2.9.0
  * Test Reports 1.2.0
  * WordPress Beta Tester 3.6.1

### Actual Results
1.  ✅ Issue resolved with patch.

### Additional Notes
- Any additional details worth mentioning.

### Supplemental Artifacts
Add as Attachment

**Comment by afragen** [comment]
### Description
Describe the security vulnerability.

### Environment
- WordPress: 6.7-RC1
- PHP: 7.4.30
- Server: nginx/1.26.1
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 7.4.30)
- Browser: Safari 18.0.1
- OS: macOS
- Theme: Twenty Twelve 4.3
- MU Plugins: None activated
- Plugins:
  * Core Rollback 1.3.6
  * Local Development 2.9.0
  * Test Reports 1.2.0
  * WordPress Beta Tester 3.6.1

### Steps to Reproduce
1. 
2. 🐞 Bug occurs.

### Expected Results
1.  ✅ What should happen.

### Actual Results
1.  ❌ What actually happened.

### Additional Notes
- Any additional details worth mentioning.

### Supplemental Artifacts
Add as Attachment

**Comment by asirota** [comment]
Ah so you want it better than I have it already. Can you convey this to GitHub issue template yaml? Or I can with ai.

**Comment by ipajen** [comment]
Questions, Help, and Support needs to have another type of template
Also would be great if "needs triage" would be added in the template when new ticket is created.

**Comment by ipajen** [comment]
In the template it could be worth adding what API host is used  on support tickets.

**Comment by ipajen** [comment]
Closing ticket as the template is on place and improvements can be made in a new ticket.
