### ISSUE TITLE
If AU plugin is deleted, data should be removed from database

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#101]
If the AU plugin is deleted. Any data in the database should be removed same time the plugin is deleted.

For example:
```
in wp_options:
aspirepress_settings
aspireupdate_settings
```

**Comment by costdev** [comment]
This should be straightforward enough.

We register an activation hook which registers an uninstall hook, which in turn deletes the options.

Something like:

```php
register_activation_hook( __FILE__, '\AspireUpdate\activation_hook' );

function activation_hook() {
    register_uninstall_hook( __FILE__, '\AspireUpdate\uninstall_hook' );
}

function uninstall_hook() {
    delete_site_option( 'aspirepress_settings' );
    delete_site_option( 'aspireupdate_settings' );
}
```

**Comment by namithj** [comment]
Need to add check and branch for multisite too

**Comment by costdev** [comment]
While the callstack for `delete_site_option()` accounts for multisite, there's a slight performance improvement by having:

```php
if ( is_multisite() ) {
    delete_option( $this->option_name );
} else {
    delete_network_option( null, $this->option_name );
}
```

That said, the performance improvement is likely negligible, especially since this will only run once in an execution.
