### ISSUE TITLE
PCP warning in class-themes-screens.php

### ISSUE THREAD

**Issue by namithj** [aspirepress/AspireUpdate#107]
Can we fix these?

Line | Column | Type | Code | Message
93 | 20 | WARNING | WordPress.Security.NonceVerification.Recommended | Processing form data without nonce verification.
93 | 52 | WARNING | WordPress.Security.NonceVerification.Recommended | Processing form data without nonce verification.
93 | 52 | WARNING | WordPress.Security.ValidatedSanitizedInput.InputNotSanitized | Detected usage of a non-sanitized input variable:

**Comment by costdev** [comment]
Sure, you can assign me for this one. :slightly_smiling_face:

**Comment by namithj** [comment]
I can't find anyone including me in the assignee or reviewer list for some reason, do self assign.  I also have PRs pending for review which I can't assign to anyone for the same reason.

**Comment by costdev** [comment]
Thanks @ipajen! I can't seem to self-assign 🤔

**Comment by ipajen** [comment]
Sound like it might be how the permissions is set on the repository. @asirota can you boost so they have at least triage  ? 🙏

**Comment by ipajen** [comment]
https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

**Comment by asirota** [comment]
@sarah-savage I thought the idea is to have me assign and not allow self assignment. I don't think we want that do we?
