### ISSUE TITLE
Let's make the api key allow empty values for now

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#110]
Let's take off the requirement to have an api key before you save for now. Once the api key server is working the empty key should not be allowed any more.

**Comment by ipajen** [comment]
![IMG_8556](https://github.com/user-attachments/assets/b8b95095-0a02-49fa-bd29-0c15b47f494d)

it’s possible if you choose other already.

**Comment by asirota** [comment]
Or how about we just fill in `Project Voltron` for the default key and leave it at that for now.

**Comment by ipajen** [comment]
To understand this ticket better, what problem is it trying to solve? When looking in the slack chat it was they wanted to send a request without a key (possible with other API host), but maybe i misunderstood.

**Comment by asirota** [comment]
The current UI returns  404 when the api key is empty so something has to be there currently to allow settings to be saved. This could lead to confusion for the user who doesn't realize a fake key can be entered for now until the API key generation is available in AspireCloud.

**Comment by ipajen** [comment]
Its not the empty key that returns the 404, its when clicking the key symbol to get a key that gives 404. (the error handling should be improved for keys)

 If the key is empty and clicking save it will give validation. 

![emptyapikey](https://github.com/user-attachments/assets/d8809240-6874-49af-881c-eaf886d33460)

**Comment by asirota** [comment]
Right. But without something in the key the ui won't allow saving the settings to enable rewrite. We are awaiting the api key gen but for now we could ignore the empty key and remove the validation code.
