### ISSUE TITLE
Plugin Build Process to create dist version of plugin from Main

### ISSUE THREAD

**Issue by namithj** [aspirepress/AspireUpdate#120]
Plugin Build Process to create dist version of plugin from Main Branch

**Comment by afragen** [comment]
Are you looking for an automatic zip file creation from a GitHub Action?

**Comment by namithj** [comment]
I want thinking about a cleaned up branch, but a zip file would be good too, something we can link to from aspirepress.org

This should be a manually triggered action or based on a specific branch other than main.

**Comment by costdev** [comment]
We could also just do it when a commit is tagged to minimize the need for other branches
