### ISSUE TITLE
Voltron ascii code shown directly

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#122]
On desktop, edge browser.

1. Update to latest code
2. Go to : `/blog/wp-admin/index.php?page=aspireupdate-settings` and its shown directly.

There seems to be a ASCII voltron code implemented. 

I cant see a story related to this?
Who made the ascii design? on what license ?

![ascii](https://github.com/user-attachments/assets/11ff0a87-038d-4de4-a485-d9d1658b0b52)

**Comment by namithj** [comment]
Clear Cache.

**Comment by ipajen** [comment]
not shown directly after clearing cache. 
What is it for?  Its messing up on IOS phone as its not responsive (cache cleared)

@asirota Do you know what is this?, Cant find a story for it.

**Comment by asirota** [comment]
There is no story. It's a hidden Easter egg.

**Comment by namithj** [comment]
It was cache, it loads only after prolonged hover.  We should remove it from mobile devices as shrinking it to make it responsive wont work for very small font sizes.  Will push a PR  for that tomorrow..

**Comment by ipajen** [comment]
Closing ticket as now it doesn't show it on mobile devices.
