### ISSUE TITLE
Rename the GitHub repository from AspireUpdate to aspire-update

### ISSUE THREAD

**Issue by afragen** [aspirepress/aspireupdate#140]
The GitHub repository name is used as the slug for WP plugins. The WP guidelines suggest the slug should be lowercase and use dashes and not spaces.

To conform the repository name should be changed from `AspireUpdate` to `aspire-update`.

There will be 2 issues related to this change.

1. Any currently installed plugin will need to be re-activated due to the slug change.
2. The text domain will need to change in all places.

**Comment by asirota** [comment]
Strictly speaking there is no space. And is AspireUpdate not logically equivalent to aspireupdate? Would seem things are not case sensitive but are they?

**Comment by afragen** [comment]
I believe it will depend on the user's server as to whether it is case sensitive. The safest choice is to remove it as an issue.

**Comment by namithj** [comment]
Should it be aspireupdate or aspire-update.

**Comment by afragen** [comment]
@namithj That's the question.

**Comment by namithj** [comment]
I prefer aspire-update as it makes sense with the usual plugin naming convention of each word separated by a hyphen but its confusing whether AspireUpdate is a single name or Aspire Update.

**Comment by ipajen** [comment]
AI says
For consistency and readability, it’s generally best to use aspire-update with a hyphen, as it follows common naming conventions in software projects. Hyphens improve clarity and make it easier to distinguish separate words in a compound name. However, if AspireUpdate or aspireupdate is already in use and consistent across other documentation or repositories, it may be worth sticking with that to avoid confusion.

but personally I like aspireupdate more

**Comment by ipajen** [comment]
Remember to update docs links on https://github.com/aspirepress/documentation

and translation files on
https://github.com/aspirepress/AspireUpdate/tree/main/languages

**Comment by asirota** [comment]
This feels a little make work to me gang. 

Can we just change the slug to `aspireupdate` ? I think the docs will keep working.

**Comment by namithj** [comment]
Keep everything as it is and just lowercase the zip generation?

**Comment by yosefeliezrie** [comment]
@asirota 

https://aspirepress.slack.com/archives/C07Q88M2KQF/p1730813797643319

This will give a bit more context but should comment here. 

In addition. Checking the [WordPress plugin handbook](https://developer.wordpress.org/plugins/plugin-basics/best-practices/) there are a few things we should fix perhaps: 

- Folder structure and file names should be aspire-update
- We need to separately check that the function names in class names align with to WPCS and the plugin handbook. 
- We need to avoid using ap_ as prefix and instead use AspirePress see handbook.

**Comment by namithj** [comment]
Lets move this onto #144

**Comment by afragen** [comment]
Just letting everyone know that GlotPress changes the slug to lowercase, so AspireUpdate exports PO files from GlotPress to `aspireupdate-{$locale}.po`.

**Comment by afragen** [comment]
Also, #144 is locked to only collaborators. ☹️

**Comment by asirota** [comment]
I've unlocked it. Not sure how it was even locked. Maybe I did it when transferring the issue.

**Comment by afragen** [comment]
This can be fixed by the action taken to lowercase the repository.

Related: https://github.com/aspirepress/aspireupdate/pull/193
