### ISSUE TITLE
 Call to AP only made if SSL is disabled

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#15]
If I disable ssl verification then call to aspire AND wp is made. Otherwise only Wp.

**Comment by smileBeda** [comment]
I _believe_ this is what was "fixed" here: https://github.com/aspirepress/AspireUpdate/commit/fda8ddcfa368db4214f4a2159a58dd7cdb52ebae
This would now be in main, so it might be resolved at this point.

**Comment by smileBeda** [comment]
@sarah-savage can you confirm the above? As such this would be fixed, but needs future work.

**Comment by namithj** [comment]
This is not fixed in #25
