### ISSUE TITLE
Add a notice  when settings are saved 

### ISSUE THREAD

**Issue by harikrishnanr994** [aspirepress/AspireUpdate#155]
https://github.com/user-attachments/assets/34b8be95-dfc4-4df8-a52b-9873873fb002

When I press the Save changes, the screen just flashes for a second and I do not get any response if it is saved or not. No errors detected in console. View video attachment.

**Comment by asirota** [comment]
Let's add a settings saved notice so it shows something happened, this doesn't seem to happen when the plugin is under the dashboard menu.
