### ISSUE TITLE
GUI improvement of api host boxes in advanced mode

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#16]
On iOS mobile it’s uncertain what boxes belongs together. Se pics. As first is alone and 2 and 3 box is grouped.

![IMG_8412](https://github.com/user-attachments/assets/12eb18e6-d899-4c03-acba-b30ed17f32fb)

**Comment by asirota** [comment]
Yeah that's confusing I agree. The idea is to show which api is being replaced with another. So I'm not positive I understand why there are multiple boxes here at all.

**Comment by namithj** [comment]
The Hosts box now only contains one field per host.  This issue no longer exists

#25
