### ISSUE TITLE
Add New Plugin - call only to WP and not AP

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#17]
if I go to /wp-admin/plugin-install.php only a call is made to Wp and not to AP

plugins_api()
wp-admin/includes/plugin-install.php:173
WP_Plugin_Install_List_Table->prepare_items()
wp-admin/includes/class-wp-plugin-install-list-table.php:242

**Comment by namithj** [comment]
@smileBeda Is this valid with the new version?  Please close if resolved.

**Comment by ipajen** [comment]
Its working now, but when "Install now" is used it doesn't go to AP simular to https://github.com/aspirepress/AspireUpdate/issues/28
