### ISSUE TITLE
Consider putting Voltron in its own file.

### ISSUE THREAD

**Issue by afragen** [aspirepress/AspireUpdate#171]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Put Voltron code in its own file and simply `include_once()` where needed.

### Mockups or Images of the feature

n/a

**Comment by namithj** [comment]
This can be closed

**Comment by ipajen** [comment]
Closing ticket as Voltron still works on desktop and not shown on mobile.
