### ISSUE TITLE
Readme.me missing license 

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#18]
plugin has no license declared on the readme.me file GPLv2 (or later)

**Comment by smileBeda** [comment]
https://github.com/aspirepress/AspireUpdate/pull/23/

**Comment by smileBeda** [comment]
_should_ be fixed by upcoming PR of namithj - thus closed my PR in regard and unassigned myself from the ticket.

**Comment by namithj** [comment]
License added in Plugin Header as per #23
