### ISSUE TITLE
[Bug]: Attempt to read property "slug" on false

### ISSUE THREAD

**Issue by ipajen** [aspirepress/aspireupdate#188]
### What happened?

Using the translation bransch and getting following Warning.

```
Attempt to read property "slug" on false
wp-content/plugins/AspireUpdate/vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack.php:63
Fragen\Translations_Updater\Language_Pack->run()
wp-content/plugins/AspireUpdate/vendor/afragen/translations-updater/src/Translations_Updater/Base.php:52
Fragen\Translations_Updater\Init->get_remote_repo_data()
wp-content/plugins/AspireUpdate/vendor/afragen/translations-updater/src/Translations_Updater/Init.php:78
Fragen\Translations_Updater\Init->run()
wp-content/plugins/AspireUpdate/aspire-update.php:76
aspireupdate_init_translations()
wp-includes/class-wp-hook.php:324
do_action('init')
wp-settings.php:704
```
**Edit by @costdev**: Just making it a code block for easier reading.

### Version

Nightly

### OS

None

### What browsers are you seeing the problem on?

Microsoft Edge

### WordPress

6.7

### PHP

8.3.12

### Server

8.3.12

### Database

mysqli (Server: 10.6.20-MariaDB / Client: mysqlnd 8.3.12)

### Theme

Twenty Twenty-Four 1.3

### Must-Use Plugins

 * block-automation-by-installatron.php   * Health Check Troubleshooting Mode 1.9.2   * ManageWP - Worker Loader 1.0.0

### Plugins

* Accessibility Checker 1.16.1   * Advanced Custom Fields 6.3.0   * Advanced Database Cleaner 3.1.5   * All-in-One WP Migration 7.87   * AspireUpdate 0.6   * Code Snippets 3.6.5.1   * Cron Logger 1.3.0   * Debug Log Helper 1.5.3   * Git Updater 12.6.0.1   * GlotPress 4.0.1   * GP Auto Extract 1.1   * HD Quiz 1.8.15   * Limit Login Attempts Reloaded 2.26.14   * Loco Translate 2.6.11   * ManageWP - Worker 4.9.20   * Ninja Forms 3.8.18   * OMGF 5.9.1   * Performance Lab 3.5.1   * Plugin Check (PCP) 1.2.0   * Plugin Compatibility Checker 4.0.1   * Query Monitor 3.16.4   * RSS Importer 0.3.2   * Stop User Enumeration 1.6.3   * Test Reports 1.2.0   * WP Crontrol 1.17.0

### Relevant debug log output

```shell
[14-Nov-2024 08:27:15 UTC] PHP Warning:  Attempt to read property "slug" on false in /home/XX/public_html/blog/wp-content/plugins/AspireUpdate/vendor/afragen/translations-updater/src/Translations_Updater/Language_Pack.php on line 63
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by namithj** [comment]
Dependency issue?

**Comment by costdev** [comment]
Assigning @afragen to look into whether this is an implementation issue or an issue in the translations-updater.

**Comment by afragen** [comment]
I'll take a look. Thanks.

**Comment by ipajen** [comment]
Correct the `translations bransch `from `aspirepress/AspireUpdate`

 I’m not sure if it’s related, but I received a 403 rate limit error from GitHub for Git Updater around when this issue occurred.

Also, I no longer get the warning, but for some reason, I’m not seeing any calls to the translation package. Let me know if you’d like an account on my test site to check things out.

**Comment by afragen** [comment]
I found the issue. GlotPress converts mixed cases to lowercase. As `AspireUpdate` becomes `aspireupdate` on export from GlotPress, so `aspireupdate-de_DE.po` instead of `AsprieUpdate-de_DE.po`. Simply changing the `Text Domain` header in the main plugin file doesn't complete the action. All the `__('string', 'AspireUpdate')` lines of code need to be `__('string', 'aspireupdate')`.

This prevents the translations from being loaded.

**Comment by namithj** [comment]
We will have to rename the plugin folder to all lowercase for that.  Something I think we should actually do to follow naming conventions within wordpress

**Comment by afragen** [comment]
We actually don't need to rename the plugin folder, but we should. The `slug` variable is set in `$config` and is lowercase.

**Comment by afragen** [comment]
But it will cause Plugin Check plugin to show errors cause they use the folder name as the slug.

**Comment by afragen** [comment]
@ipajen hsve you seen this any more. I'm not able to replicate it.

**Comment by ipajen** [comment]
Lets close this. After the lower case fix,  I haven't seen it anymore.

**Comment by ipajen** [comment]
Reopening this issue.
The PHP warning comes when the API call to github is not success. (https://api.github.com/repos/aspirepress/aspireupdate-translations/contents/language-pack.json?ref=main) and github respons 403 Forbidden becuase of rate limit.
[](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28)

On shared hosting this could eventually be a problem as the IP is the same as other plugins could make calls to Github. 

As I am testing I have changed the protected static $hours for caching to recreate the problem.

It would be good to have a null check that values are there or what is called so the PHP warning is not thrown  `Attempt to read property "slug" on false`

**Comment by afragen** [comment]
@ipajen can you test this change and let me know?

https://github.com/afragen/translations-updater/commit/2d2f6e4dc621537ea243bc00b0e4c096a19b90a1
