### ISSUE TITLE
exclude files from build

### ISSUE THREAD

**Issue by ipajen** [aspirepress/aspireupdate#189]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

.cache folder with .gitkeep file
.DS_Store file

Could this files be excluded and what purpose does the .DS_Store file have?

As PCP say "application_detected" and "hidden_files"

### Mockups or Images of the feature

![files](https://github.com/user-attachments/assets/d722a5c2-2663-4111-9e44-88c4c12a35bf)

**Comment by namithj** [comment]
Which branch is this?  There are already git ignored files.

**Comment by ipajen** [comment]
main, playground-ready, translate has this issue.

**Comment by asirota** [comment]
People's local files leaked onto the repo. .gitignore should have these references already. 

If we delete them they will most likely creep in again during PRs that people do.

**Comment by ipajen** [comment]
@asirota Would it possible to delete them and then make a rule on merge that fails the merge if there is forbidden files?

**Comment by costdev** [comment]
Reopening to handle the `.cache` directory element of this issue.
