### ISSUE TITLE
Wrong url shown in Downloading update from

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#19]
Go to /blog/wp-admin/update-core.php?action=do-plugin-upgrade and choose your plugin to update

the text says 
Downloading update from https://downloads.wordpress.org/plugin/seo-by-rank-math.1.0.230.zip…

I am expecting  it would  say AP as if I try the direct link it works to get the download.
![IMG_8414](https://github.com/user-attachments/assets/89231577-c7b3-42a0-8e0f-fb24244e75a2)

**Comment by ipajen** [comment]
Same issue if trying to reinstall WP

Update WordPress
Downloading update from https://downloads.wordpress.org/release/wordpress-6.6.2-no-content.zip…

Download failed.: Not Found

Installation failed.

**Comment by namithj** [comment]
Yes, we have only focused on the API, right now.  

Need to move this into a feature update and discuss the implementation

**Comment by namithj** [comment]
This will start working when AspireCloud starts serving files locally.
