### ISSUE TITLE
[Bug]: Translations require lowercase textdomain

### ISSUE THREAD

**Issue by afragen** [aspirepress/aspireupdate#192]
### Contact Details

andy@thefragens.com

### What happened?

GlotPress exports files as lowercase, not mixed case. Consequently all the text domains need to be switched to lowercase for the translations to load. Also we no longer need to call `load_plugin_textdomain`.

### Version

0.5 (Default)

### OS

MacOS

### What browsers are you seeing the problem on?

Safari

### WordPress

6.7

### PHP

8.2

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by ipajen** [comment]
Closing ticket as we have lowercase now.
