### ISSUE TITLE
Generate POT using GA on tagged release

### ISSUE THREAD

**Issue by afragen** [aspirepress/aspireupdate#195]
### I have checked the following:

- [X] I've searched existing issues and found nothing related to my issue.

### Describe the feature you want to add

Add a GitHub Action to generate a POT on a release.

### Mockups or Images of the feature

 na

**Comment by asirota** [comment]
https://github.com/varunsridharan/action-wp-pot-generator

**Comment by afragen** [comment]
I actually made a PR to the above GA to fix a bug and provide more functionality. If it's merged great otherwise I'll consider switching to my fork.

**Comment by afragen** [comment]
Closing the issue as PR merged.
