### ISSUE TITLE
Cannot check Override Default API in settings

### ISSUE THREAD

**Issue by mzalewski** [aspirepress/AspireUpdate#20]
### Repro Steps
1. Log in to WordPress
2. Navigate to Aspire Update Settings (advanced=true)
3. Check the 'Override Default API' checkbox
3a. Ensure the 'Override Default Downloads' checkbox is unchecked
4. Click Save

Current Behaviour: After reload, the Override Default API checkbox is unchecked again

Expected behaviour: Override Default API checkbox should remain checked

### Other notes:
This only happens when the other checkbox (Override Default Downloads) is unchecked.

**Comment by ipajen** [comment]
I can confirm I have the same issue as above.

**Comment by namithj** [comment]
The option is removed

https://github.com/aspirepress/AspireUpdate/pull/25
