### ISSUE TITLE
[Bug]: Fix reference to version in `varunsridharan/action-wp-pot-generator`

### ISSUE THREAD

**Issue by afragen** [aspirepress/aspireupdate#203]
### Contact Details

andy@thefragens.com

### What happened?

Action failed. I didn't reference the GA version correctly.

### Version

0.5 (Default)

### OS

None

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by costdev** [comment]
@afragen Action failed. Try `@2.0` instead
