### ISSUE TITLE
Handling API Keys within the Plugin UI

### ISSUE THREAD

**Issue by namithj** [aspirepress/AspireUpdate#36]
1) Create a new dropdown with two options "Aspire Cloud" and "Others". 
2) Choosing Others will show a text box where users can manually enter a host.
3) There will only be one host at a time
4) The Generate API Key button will use this host to fetch the API Key

### Discussed in https://github.com/aspirepress/AspireUpdate/discussions/35

<div type='discussions-op-text'>

<sup>Originally posted by **namithj** October 21, 2024</sup>
Currently we have the API key as a separate fields and it needs to be repeated for each host so that there can be an API key for each host.

I am thinking about using the API Key end point for dual purposes 
a) To Get an API Key
b) To Make sure we are dealing with an actual mirror

We can also rename the API endpoint to something else like Handshake or hello to make more sense in this role if required.

This is the proposed workflow

1) User enters a Host Domain

2) The Plugin tries to ping the API Key domain.

3a) The plugin receives an API Key (blank key is also fine if the host doesnt want to use an API key). We go to Step 5
3b) The plugin is unable to find the API Key endpoint.

4) We show an error message to the user and refuse to save the new host

5) If the host is approved or a failed host is removed we save the host.

6) System uses one of the added hosts randomly to ping (This can actually be finalized later if we want to prioritize or lock particular installations to a particular host etc)
</div>

**Comment by asirota** [comment]
looks and sounds good for now
