### ISSUE TITLE
No values for aspirecloud on mobile

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#40]
On mobile there is an empty box when the aspire is used. I am expecting it to be same as on desktop. Se pictures 
**On iOS 18.0.1 iPhone SE Safari** 

![IMG_8465](https://github.com/user-attachments/assets/8d1256c9-a906-4126-841e-75ae6ec64beb)

**on desktop edge browser**
![IMG_8463](https://github.com/user-attachments/assets/bd68a094-2c19-43f0-bafd-4aedd6e79efe)

**Comment by namithj** [comment]
Can you check if this is cache

**Comment by ipajen** [comment]
Closing as it was a cache issue.
