### ISSUE TITLE
Update Text domain to AspireUpdate

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#41]
Now the text domain is aspiredomain and it would be great if it could be AspireUpdate instead.

Even if we don’t use the plugin check there could be end users who does this and to avoid noise it could be worth fixing as who knows for future maybe this plugin could be in the Wp repo…

WordPress.WP.I18n.TextDomainMismatch

Mismatched text domain. Expected 'AspireUpdate' but got 'aspireupdate'

**Comment by namithj** [comment]
so change from all lowercase to the capitalized version.  Thats a weird recommendation from plugin check!

**Comment by ipajen** [comment]
Closing as warnings above are gone now.
