### ISSUE TITLE
Debug logging should write debug log no matter whether API_REWRITE is on or not

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#43]
If debug logging is turned on log all data even if the offical worg repo is being used

**Comment by asirota** [comment]
To be clear - no matter whether the default AP_HOST is used or Other is used, when Debug logging is turned on,it should write a debug log
![image](https://github.com/user-attachments/assets/7e2b02d8-5013-43e4-8b3b-f55952279035)

**Comment by ipajen** [comment]
Reopening as not tested
