### ISSUE TITLE
Debug doesn’t log if rewrite is not enabled

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#44]
The debug should logs even if rewrite is not enabled according to

https://aspirepress.slack.com/archives/C07Q88M2KQF/p1729794182520539?thread_ts=1729793528.343269&channel=C07Q88M2KQF&message_ts=1729794182.520539

**Comment by ipajen** [comment]
Closing as https://github.com/aspirepress/AspireUpdate/issues/43

**Comment by ipajen** [comment]
@asirota Just to confirm, now its logging with this fix the API calls but not calls for other than api.wordpress.org, for example:

Downloading update from https://downloads.wordpress.org/plugin/hd-quiz-save-results-light.0.7.0.zip…
GET | https://wordpress.org  from health check
https://ps.w.org/advanced-database-cleaner/assets/banner-772x250.png?rev=1630620
https://ts.w.org/wp-content/themes/extendable/screenshot.png?ver=2.0.13?ver=2.0.13

Should it also log above?

**Comment by namithj** [comment]
Those assets will be served by aspire cloud once it's up.  We are not tracking assets.
