### ISSUE TITLE
PHP Warning:  Constant AP_HOST already defined 

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#46]
in wp-config
`define( 'AP_HOST', 'api.aspirecloud.org' );
define( 'AP_REMOVE_UI', true );
define( 'AP_API_KEY', true );`

gives:
`[24-Oct-2024 19:32:55 UTC] PHP Warning:  Constant AP_HOST already defined in /home/khaotiptha/domains/xxx/public_html/blog/wp-config.php on line 94

[24-Oct-2024 19:32:55 UTC] PHP Warning:  Constant AP_API_KEY already defined in /home/khaotiptha/domains/xxx/public_html/blog/wp-config.php on line 96
`
When checking wp-config define lines are only once, and the define( 'AP_REMOVE_UI', true ); works fine.

**Comment by costdev** [comment]
I can't seem to reproduce this issue.

Can you produce this using just a fresh site install, the AspireUpdate plugin, and the `wp-config.php` changes?

**Comment by ipajen** [comment]
Tried on a new local WP instance i still get the same issue.
`define( 'AP_HOST', 'api.aspirecloud.org' );
define( 'AP_REMOVE_UI', true );
define( 'AP_API_KEY', false);
define( 'AP_ENABLE', true);`

gives:
`Warning: Constant AP_HOST already defined in C:\wamp64\www\w\wp-config.php on line 100

Warning: Constant AP_API_KEY already defined in C:\wamp64\www\w\wp-config.php on line 102

Warning: Constant AP_ENABLE already defined in C:\wamp64\www\w\wp-config.php on line 103`

**Comment by costdev** [comment]
Hmm :thinking_face:

Just double checking, even just to rule it out:

You're defining these between [these lines](https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php#L90-L94), correct?

**Comment by ipajen** [comment]
Thanks @costdev  It worked when i just moved the lines a few lines up. Closing this ticket.

**Comment by asirota** [comment]
I added a note to the readme on the #45 branch
