### ISSUE TITLE
Other hosts with https will be httpshttps

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#47]
minor issue but for improvement.

If i choose another host and  for example enters **https://api.aspirecloud.org**. The value is accepted and saved but then AP plugin will try with

POST | **https://https://**api.aspirecloud.org/plugins/update-check/1.1/ | cURL error 6: Could not resolve host: https

and http will be http://http://api.aspirecloud.org/themes/update-check/1.1/

Would be great if only domains could be saved or better helptext in GUI that the domain should be entered without http/https to make it easier to end users to avoid faults.

**Comment by costdev** [comment]
Also noting that trailing slashes are retained as well.

Maybe we should run it through `parse_url( $url, PHP_URL_HOST )` to resolve both issues. See [this 3v4l](https://3v4l.org/g0b5g).

Does anyone see any potential issues?

**Comment by namithj** [comment]
We still need to validate in frontend.

**Comment by costdev** [comment]
Are you thinking with JS or just a `pattern` attribute? If the latter, how strict should we be with the pattern?

**Comment by namithj** [comment]
I was thinking JS.  A pattern might become too cryptic once we write it for different use cases making it difficult for future modifications

1) automatically remove the protocol on field blur
2) validate for domain, subdomain and extension structure
3) remove any special characters

**Comment by costdev** [comment]
That sounds good, and it follows the number 1 rule of Regex: Don't use Regex, if you can avoid it.

**Comment by ipajen** [comment]
Problem still exist after #61 its adding https:// ex.  https://https://api.aspirecloud.org./plugins/update-check/1.1/

**Comment by namithj** [comment]
Can you make sure cache is refreshed on your browser.  The plugin should be removing the protocol part as you update the other hosts value automatically.

**Comment by ipajen** [comment]
Confirmed. It was a caching issue. It works fine now. closing ticket.
