### ISSUE TITLE
README: Descriptions and Defaults for `AP_ENABLE` and `AP_API_KEY` are reversed.

### ISSUE THREAD

**Issue by costdev** [aspirepress/AspireUpdate#50]
In the README:

Configuration Parameter | Description | Default, if any
-- | -- | --
AP_ENABLE | The API Key for AspireCloud (not currently enforced) | none
AP_API_KEY | Enable API rewrites | true

The Descriptions and Defaults should be reversed.

**Comment by asirota** [comment]
Fixed in pr #48
