### ISSUE TITLE
The documents has one space after AP_DEBUG_TYPES

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#54]
the code:
`// Works as of PHP 7
define('AP_DEBUG_TYPES ', array(
    'string', 'request', 'response'
));`
in documents has one space after AP_DEBUG_TYPES , making if you copy it directly the logging will not work until you remove the space from wp-config.

**Comment by asirota** [comment]
Fixed on the README branch -- will PR once we get some more eyes on it. Thanks

**Comment by ipajen** [comment]
Closing as resolved in #55
