### ISSUE TITLE
If there is no debug-aspire-update.log there will come a PHP warning first time until there exist a log file.

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#57]
Minor improvement.

If there is no debug-aspire-update.log there will come a PHP warning first time until there exist a log file.

to recreate
1. Remove debug.log and debug-aspire-update.log
2. Activate rewrites and enter other hosts 123456
3. enable debug and for example strings type and save
4. go to dashboard - updates

Now a PHP warning will come for debug-aspire-update.log but not debug.log  (Yes it will log in `PHP Warning:  wp_update_plugins(): An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the ...` )

Excepted same behavior as debug.log (if no file exist it doesn't give a PHP warning about it)

As when testing the debug-aspire-update.log are removed and getting the PHP warnings is clutter when using QM.

`
Warning | file_get_contents(/home/khaotiptha/domains/piironen.se/public_html/blog/wp-content/debug-aspire-update.log): Failed to open stream: No such file or directory`

`wp-admin/includes/class-wp-filesystem-direct.php:39
file_get_contents()
wp-admin/includes/class-wp-filesystem-direct.php:39
WP_Filesystem_Direct->get_contents()
wp-content/plugins/AspireUpdate/includes/class-debug.php:62
AspireUpdate\Debug::log()
wp-content/plugins/AspireUpdate/includes/class-debug.php:101
AspireUpdate\Debug::log_string()
wp-content/plugins/AspireUpdate/includes/class-api-rewrite.php:67
AspireUpdate\API_Rewrite->pre_http_request()
wp-includes/class-wp-hook.php:324
apply_filters('pre_http_request')
wp-includes/class-wp-http.php:259
WP_Http->request()
wp-includes/class-wp-http.php:620
WP_Http->post()
wp-includes/http.php:202
wp_remote_post()
wp-includes/update.php:441
wp_update_plugins()
wp-includes/class-wp-hook.php:324
do_action('load-update-core.php')
wp-admin/admin.php:385`

**Comment by namithj** [comment]
The warning is being thrown because of the wrong host entry, the log file is being recreated.  You are not seeing repeated warning as the update check runs on a scheduler, you can click check again to see the warning again.  its unrelated to debug file existing

We will have validation for hosts once the api end points are up on aspirecloud

**Comment by ipajen** [comment]
@namithj The problem is not wrong hosts. I just using it as example to recreate the issue. The problem is that AP is not checking if the log file exist before opening the file(same as Wp doing) The issue still exist.
