### ISSUE TITLE
Add Unit tests (Partial coverage)

### ISSUE THREAD

**Issue by namithj** [aspirepress/AspireUpdate#63]
Add Unit tests (Partial coverage)

**Comment by costdev** [comment]
Some questions:
1. Are we going to be working from a development branch once this is implemented, or are we going to have a build process that excludes development files from releases?
2. Are we planning to use PHPUnit, or another?
3. Are we going to add E2E tests as well?

**Comment by namithj** [comment]
1) Not decided
2) Phpunit
3) Yes
