### ISSUE TITLE
Hiding featured and favourite tabs in plugins

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#74]
We need to hide features and favourite tabs on plugins when rewrite url is turned on. 

Related to #72

**Comment by asirota** [comment]
https://github.com/aspirepress/AspireUpdate/issues/72#issuecomment-2447686941

**Comment by afragen** [comment]
I think the `install_plugin_tabs` filter can do this.

**Comment by ipajen** [comment]
How come the “featured “ was not removed in the same time ?
How come they need to be removed ?
Adding how it looks in ClassicPreas when they are gone.

![IMG_8533](https://github.com/user-attachments/assets/7e5f2cdf-fdd3-4082-b529-ac0fc90d89b2)


![IMG_8532](https://github.com/user-attachments/assets/5390b1a3-ba3f-424f-8171-a75d7d3b69c6)
![IMG_8531](https://github.com/user-attachments/assets/760f2aaf-3d9b-4051-8c8b-950580ba5a6f)

![IMG_8534](https://github.com/user-attachments/assets/9bf9afa6-7260-4469-9296-041056ecd59a)

**Comment by costdev** [comment]
@ipajen Try the PR again, I made a mistake by removing the Popular tab and not the Featured tab.

**Comment by namithj** [comment]
We actually have to remove all four tabs but need to decide on something to put in place of atleast one of them to maintain the layout
