### ISSUE TITLE
Update docs about mu-plugin

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#76]
The docs needs to be updated with instructions how AU can be used as a mu-plugin

**Comment by afragen** [comment]
Consider looking at this generic mu-loader plugin. It allows loading any plugin from `wp-content/plugins` as an mu-plugin but continues to let the plugin be updated in the usual manner.

https://gist.github.com/afragen/9117fd930d9be16be8a5f450b809dfa8

**Comment by asirota** [comment]
Related to #79
