### ISSUE TITLE
Add support for Git-updater for testing

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#77]
For testing it would be helpful to add full support when using Git-updater, so its easy to get the latest code from any bransch when testing in WordPress.

In the aspire-update.php file add some headers:
GitHub Plugin URI: https://github.com/aspirepress/aspireupdate
Primary Branch: main

Docs:  https://git-updater.com/knowledge-base/required-headers/

**Comment by afragen** [comment]
Yes, this looks correct.

**Comment by afragen** [comment]
I'm so excited that someone reads/refers to the KB.
