### ISSUE TITLE
Hiding 'Favourites' tab in themes

### ISSUE THREAD

**Issue by costdev** [aspirepress/AspireUpdate#81]
We need to hide the 'Favourites' tab on themes when rewrite url is turned on.

Related to #72 and #74.

**Comment by ipajen** [comment]
No features in themes. There a feature filter but  that’s something else.


![IMG_8535](https://github.com/user-attachments/assets/2d9f80e8-c5ba-4418-9f5a-5c770308929a)

**Comment by costdev** [comment]
Themes are treated differently - the tabs are hardcoded in `theme-install.php`. [Ref](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/theme-install.php#L210-L215)

We can hide the 'Favorites' tab using CSS, but we'd probably also have to redirect `?browse=favorites` to `theme-install.php` and let it do it's normal redirect to the behaviour of `wp.themes.router.on('route:sort')`. Currently, Core redirects to `?browse=popular`, but for forward compatibility, we should redirect to `theme-install.php`. [Ref](https://github.com/WordPress/wordpress-develop/blob/trunk/src/js/_enqueues/wp/theme.js#L2043-L2054)

Thoughts?

**Comment by yosefeliezrie** [comment]
I know this has already had a PR but commenting here. 

If we are disabling native functionality like favourites we should have a toggle for the user to disable this functionality and/or also document this well. 

Even the user has enabled rewrites they may still be looking for this functionality. Related to issue #73

Tagging @asirota as this may be docs related as well.

**Comment by costdev** [comment]
Good point @yosefeliezrie

For now, I think we can continue to use the `enable` option and document it, and when we've decided on how we want to implement the toggle, we can swap the `enable` option for the new detection.

For example, it may not be a user decision, but rather an API decision, so if a tab is supported by an API, we show it, otherwise we continue to hide it.

**Comment by namithj** [comment]
@yosefeliezrie We have to disable those tabs as there is some ambiguity about how w.org allots featured status to plugins and even allegations of payments involved in it.  We need to have a proper system in place if we ever want to do a featured list, until then we don't have any data to serve for those requests. Same goes for favourites, it's linked to individual users w.org accounts and not replicable by us until we reach a critical mass.
The only tab we can possibly implement at this point is the popular plugins tab.
