### ISSUE TITLE
Add support for a Coding Standard

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#85]
A suggestion by @costdev has been made to add support for PHP Code Sniffing to enforce coding standards. We will need to set some or adopt the defaults. 

Project link: https://github.com/PHPCSStandards/PHP_CodeSniffer/

Any feedback? What coding standard(s) should we agree upon?

**Comment by costdev** [comment]
I would suggest we begin with the WordPress-Extra standards, and then look at some of the typical controversial items.

For example:
- Array syntax (pick one):
  1. `[]`
  2. `array()`
- Yoda conditions (pick one):
  1. `'value' === $variable`
  2. `$variable === 'value'`

I don't have a strict preference either way. I'm more used to `array()` and `'value' === $variable` when working in WordPress Core, but after 21 years, either option works for me.

**Comment by chuckadams** [comment]
Being that it's a plugin, I'd maybe start with the WPCS, but maybe drag it into the 21st century and use square  brackets for arrays.  I personally dislike Yoda conditions, they're a relic of an age without static analysis, but for AspireCloud I took no official position on them.

Going with WPCS means sticking with the now unmaintained phpcs (the original squizlabs version) which means it won't even know what to do with modern php, should it be used in the future.  I have a php-cs-fixer ruleset for AspireCloud based on `@PER-CS` that's mostly spelled out, just needs roomier whitespace config to mostly comply with WPCS's love of it.  https://github.com/aspirepress/AspireCloud/blob/main/.php-cs-fixer.dist.php

**Comment by costdev** [comment]
@chuckadams WPCS should be using PHPCS ^3.9.0 which is the "new" version (the last release of the "old" version was 3.7.2). 

[The Packagist listing](https://packagist.org/packages/squizlabs/php_codesniffer) was retained for downstream, but the source is from the "new" PHPCS

**Comment by chuckadams** [comment]
If WPCS using the maintained phpcs, then that seems reasonable to adopt.  But maybe with some basic 7.4 improvements like square brackets. It's not like we have to meet .org's standards here ;)

**Comment by namithj** [comment]
I don't care as long as it's added in to phpcs for auto formatting. I will use what will come out of our xml

**Comment by costdev** [comment]
Thanks! If there's nothing else to discuss on this for now, I can go ahead and get a PR up for this as soon as possible.

**Comment by namithj** [comment]
@costdev If we change the brackets will it affect passing PCP or WPCS code check included in build checks.  If it might affect something it might be we want to leave as it is for now.  I would prefer our plugin to raise ZERO flags on any code checks in repos which have WPCS implemented.

**Comment by costdev** [comment]
@namithj For build checks, these will use the same PHPCS rules that we will have locally, so the checks will be verifying that the code meets our chosen standard.

This shouldn't cause failures in Plugin Check, but when I put together the configuration, I'll run PHPCBF and check the results against Plugin Check :thumbs_up:
