### ISSUE TITLE
Add .editorconfig file to the project to enforce standards for code formatting and support in common IDEs

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#86]
.editorconfig would also be added to the project: https://editorconfig.org/

**Comment by asirota** [comment]
https://editorconfig.org/#download -> plugins for IDEs that require a plugin to respect .editorconfig

**Comment by asirota** [comment]
```
#editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false


[*.js]
trim_trailing_whitespace = false

[*.css]
trim_trailing_whitespace = false

[*.php]
trim_trailing_whitespace = false

```

spaces or tabs?
js formats, css formats, php formats.... let's discuss

Here are supported keys:
https://spec.editorconfig.org/#supported-pairs

**Comment by costdev** [comment]
For reference, [here's the one](https://github.com/WordPress/wordpress-develop/blob/trunk/.editorconfig) WordPress Core uses.

Aside from `wp-config-sample.php`, I find this represents a typical setup.

On the "spaces or tabs" question, for me personally, I'd say tabs for most, spaces for YAML. Possibly spaces for JSON if that's the preference.

**Comment by namithj** [comment]
Need to make sure these are the same ones WPCS is using. Else phpcs will format it one way and the editor another way.

**Comment by namithj** [comment]
Yeah the core one is the way to go

**Comment by costdev** [comment]
We can get a PR up pretty quickly for this, so we just need to consider two things:
- If there are other opinions we want to gather first
- Point (2) of #83

**Comment by chuckadams** [comment]
Just curious why the trim_trailing_whitespace is false for anything but markdown files?  This is the config I'm using for AspireCloud, combined with some extra file patterns I use at work:

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 4
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false

[*.{css,scss,gql,js,cjs,mjs,jsx,ts,tsx,mdx,json,vue,yml,yaml}]
indent_size = 2

[docker-compose.yml]
indent_size = 4
```

**Comment by costdev** [comment]
I might be missing something, but `trim_trailing_whitespace` is `true` for anything but markdown files.

**Comment by asirota** [comment]
I left a strawperson sample. Please improve away and let's agree to a standard across all our repos if we can.

**Comment by costdev** [comment]
@namithj Do you still agree that the WP Core `.editorconfig` is the way to go?

**Comment by namithj** [comment]
Yes, I always prefer going with what core is doing (even when they are doing things wrong) since we are building extension to the core code itself so its logical that everything matches..
