### ISSUE TITLE
Plugin and themes not hiding tabs

### ISSUE THREAD

**Issue by ipajen** [aspirepress/AspireUpdate#88]
Cleared browser cache.
1. Latest main code.
2. Got to `/wp-admin/index.php?page=aspireupdate-settings` and activate Enable AspireUpdate API Rewrites
3. Enter API KEY = x  and save changes
4. Go to /wp-admin/plugin-install.php

Expected that "favorites"  was gone.
Actual result. All the tabs is still there.

**Comment by costdev** [comment]
Testing in Playground and locally, the Favorites tab doesn't appear for me in Themes -> Add New Theme.

However, both the Featured and Favorites appears in Plugins > Add New Plugins, and this is caused by a mismerge.

Submitting a PR to resolve the mismerge momentarily.
